name: Flask App CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**"
      - "app/**"
      - "helm-charts/**"
      - ".github/workflows/continous-integration.yml"
      
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-southeast-2
  EKS_CLUSTER_NAME: flaskapp-eks-cluster
  ECR_REPOSITORY_NAME: flaskapp-dev-ecr

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426449772112:role/github-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Image Tag
        id: set-image-tag
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 426449772112.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_NAME }}:${{ steps.set-image-tag.outputs.image-tag }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.ECR_REPOSITORY_NAME }}:${{ steps.set-image-tag.outputs.image-tag }} 426449772112.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }}:${{ steps.set-image-tag.outputs.image-tag }}

      - name: Push Docker Image to ECR
        run: |
          docker push 426449772112.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }}:${{ steps.set-image-tag.outputs.image-tag }}
          
          
  deploy-to-eks:
    needs: build-and-push
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426449772112:role/github-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
      
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install my-flaskapp ./helm-charts/my-flaskapp \
            --set image.repository=426449772112.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }} \
            --set image.tag=${{ needs.build-and-push.outputs.image-tag }} \
            --namespace s-${{ needs.build-and-push.outputs.image-tag }} --create-namespace

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/my-flaskapp -n s-${{ needs.build-and-push.outputs.image-tag }} --timeout=120s      
