name: Management Infrastructure Provisioning

on:
  pull_request:
    paths:
      - "Iac/**"
      - ".github/workflows/terraform.yml"
      - "workloads/**"

  push:
    branches:
      - main
      - fix-pipe
    paths:
      - "Iac/**"
      - ".github/workflows/terraform.yml"
      - "workloads/**"

permissions:
  contents: read
  id-token: write

jobs:
  infrastructure-provisioning:
    name: Infrastructure Provisioning (VPC + EKS + IAM)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Iac/Terraform/envs/dev
    # permissions:
    #   contents: read
    #   id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426449772112:role/github-terraform-role
          aws-region: ap-southeast-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Format Check
      #   run: terraform fmt -check      

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: infrastructure-plan
          path: Iac/Terraform/envs/dev/tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

  worload-deployment:
    name: Workload Deployment (alb + Helm + kubeconfig)
    runs-on: ubuntu-latest
    needs: infrastructure-provisioning
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: Iac/Terraform/workloads/aws_alb_cont
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426449772112:role/github-terraform-role
          aws-region: ap-southeast-2

      - uses: hashicorp/setup-terraform@v3

      - name: Wait for EKS to become active
        run: |
          aws eks wait cluster-active --name flaskapp-eks-cluster --region ap-southeast-2
      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan    